### Setup
```{r}
pacman::p_load(tidyverse, rgee, sf, raster)
ee_Initialize()

ee_Initialize(drive = T)
```

```{r}
curico <- read.csv("Proyecto1Espaciales/curicolluvias.csv")

# https://climatologia.meteochile.gob.cl/application/historico/aguaCaidaHistoricaMensual/340031

```

```{r}
roi <- 
  c(-71.24031, -34.98277) %>%  #Curicó
  st_point(dim = "XYZ") %>% 
  st_buffer(dist = 0.1) %>% 
  sf_as_ee()
```

```{r}
disponible <- ee$ImageCollection('LANDSAT/LC08/C01/T1_TOA')$
  filterDate('2013-07-01','2014-07-10')$
  filterBounds(roi)$
  filterMetadata('CLOUD_COVER','less_than', 5)
```

```{r}
# ordeno las fechas
df_disponible <- ee_get_date_ic(disponible)%>%
  arrange(time_start)

# extraigo la primera
escena <- df_disponible$id[1]

# defino las bandas que me interesa extraer
l8_bands <- ee$Image(escena)$select(c("B1", "B2", "B3", "B4", 
                                      "B5", "B6", "B7", "B9"))
```

```{r}
# extraigo imagenes satelitales 
l8_img <- ee_as_raster(
  image = l8_bands,
  region = roi$bounds(),
  scale = 30)

png(file="Proyecto1Espaciales/curiplot.png", width=500, height=600)
plotRGB(l8_img, r=4, g=3, b=2, stretch = "lin")
dev.off()
```